version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
    ignore:
      - dependency-name: "codemirror"
        update-types: ["version-update:semver-major"]
